### ISSUE TITLE
Making a port of the extension to the IntelliJ platform

### ISSUE THREAD

**Issue by TheOnlyTails** [stordahl/sveltekit-snippets#1]
Hi,
I usually use WebStorm to develop project with Svelte, and I wanted to ask for your permission to port this to the IntelliJ platform (using the Live Template feature).

**Comment by stordahl** [comment]
Of course - go right ahead

**Comment by TheOnlyTails** [comment]
Great! I'll get to work.

**Comment by stordahl** [comment]
Hey @TheOnlyTails did you ever happen to port this to Intellij?! I'm thinking about building that out, but wanted to see if you had already

**Comment by TheOnlyTails** [comment]
Not really, I kinda just gave out on it.
