### ISSUE TITLE
Typescript endpoint in TS file 

### ISSUE THREAD

**Issue by sz3ry** [stordahl/sveltekit-snippets#4]
### **Problem** 

VSCode cannot operate a TS snippet because a lack of "contributes" of "typescript". 

### **Solution** 

"contributes": {
        "snippets": [
            {
                "language": "javascript",
                "path": "./snippets/snippets.code-snippets"
            },
            {
                "language": "typescript",
                "path": "./snippets/snippets.code-snippets"
            },
            {
                "language": "svelte",
                "path": "./snippets/snippets.code-snippets"
            },
            {
                "language": "html",
                "path": "./snippets/snippets.code-snippets"
            },
            {
                "language": "markdown",
                "path": "./snippets/snippets.code-snippets"
            }
        ]
    }

**Comment by stordahl** [comment]
Thanks for bringing this to my attention! I missed this in the last release. I'll get a new minor version published this weekend with this fix!
