### ISSUE TITLE
General question about updates to the snippets

### ISSUE THREAD

**Issue by newlegendmedia** [stordahl/sveltekit-snippets#8]
Love this extension! I am wondering if you are keeping the snippets up to date with the latest changes in Svelte Kit? I haven't tried comparing things but I know they have been updating the params to endpoints and some name changes on things etc.

**Comment by stordahl** [comment]
Hey @newlegendmedia!! Thanks for the kind words. tbh I've been so pre-occupied with my day job and preparing to move that I haven't been keeping this extension up to date. If you want to submit a PR with updates I'll look at it right away, but if not it may be a couple weeks until I'm able to make the updates myself.

**Comment by newlegendmedia** [comment]
Thanks - i don’t think I’ll be able to do that but I appreciate what you’ve done so far.

**Comment by jhubbardsf** [comment]
I actually had the same question. I'll probably try to update them soon and PR it.

**Comment by stordahl** [comment]
That would be great! If you don't get to it by next weekend, I should have time to update it then.
